title: Online Resume
author: Trenton Rutherford
email: ter759@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"
  Trenton Rutherfords Online Technical Skills Resume. These are all skills learnt in Emerging tech skills at the University of Tulsa
theme: minima
# social links
github_username:  trentonrutherford

show_excerpts: true # set to false to remove excerpts on the homepage
